// generated by tools/bpf_gen.zig from bpf/dns_intercept.c — do not edit
//
// regenerate with:
//   clang -target bpf -O2 -g -c -o dns_intercept.o bpf/dns_intercept.c
//   zig run tools/bpf_gen.zig -- dns_intercept.o src/network/bpf/dns_intercept.zig
//
// placeholder: this file defines the map layout and relocation structure
// needed by the loader. the actual instruction bytecode should be
// regenerated from the C source using the commands above once clang
// with BPF target support is available.

const BPF = @import("std").os.linux.BPF;

pub const MapDef = struct {
    name: []const u8,
    map_type: u32,
    key_size: u32,
    value_size: u32,
    max_entries: u32,
};

pub const maps = [_]MapDef{
    .{ .name = "service_names", .map_type = 1, .key_size = 64, .value_size = 4, .max_entries = 256 },
};

pub const Reloc = struct {
    insn_idx: u32,
    map_idx: u32,
};

// placeholder relocations — the real bytecode will have ld_imm64
// instructions referencing the service_names map at specific offsets.
// these get patched by ebpf.loadProgram() with the actual map fd.
pub const relocs = [_]Reloc{
    .{ .insn_idx = 56, .map_idx = 0 },
};

/// BPF program section: "tc_ingress"
pub const prog_name = "tc_ingress";

// placeholder instructions: minimal program that passes all packets.
// the real bytecode from clang will be ~150-200 instructions.
//
// when running without the real bytecode, the DNS interceptor won't
// do kernel-side resolution — all queries fall through to userspace
// dns.zig, which is the correct fallback behavior.
pub const insns = [_]BPF.Insn{
    .{ .code = 0xb7, .dst = 0, .src = 0, .off = 0, .imm = 0 }, // mov r0, 0 (TC_ACT_OK)
    .{ .code = 0x95, .dst = 0, .src = 0, .off = 0, .imm = 0 }, // exit
};
