// generated by tools/bpf_gen.zig — do not edit
//
// regenerate with:
//   clang -target bpf -O2 -g -c -o <name>.o bpf/<name>.c
//   zig run tools/bpf_gen.zig -- <name>.o src/network/bpf/<name>.zig

const BPF = @import("std").os.linux.BPF;

pub const MapDef = struct {
    name: []const u8,
    map_type: u32,
    key_size: u32,
    value_size: u32,
    max_entries: u32,
};

pub const maps = [_]MapDef{};

pub const Reloc = struct {
    insn_idx: u32,
    map_idx: u32,
};

/// BPF program section: "classifier/gpu_prio"
pub const prog_name = "classifier/gpu_prio";

pub const relocs = [_]Reloc{};

pub const insns = [_]BPF.Insn{
    .{ .code = 0x61, .dst = 2, .src = 1, .off = 16, .imm = 0 },
    .{ .code = 0x55, .dst = 2, .src = 0, .off = 72, .imm = 8 },
    .{ .code = 0x61, .dst = 2, .src = 1, .off = 80, .imm = 0 },
    .{ .code = 0x61, .dst = 5, .src = 1, .off = 76, .imm = 0 },
    .{ .code = 0xbf, .dst = 3, .src = 5, .off = 0, .imm = 0 },
    .{ .code = 0x07, .dst = 3, .src = 0, .off = 0, .imm = 20 },
    .{ .code = 0x2d, .dst = 3, .src = 2, .off = 67, .imm = 0 },
    .{ .code = 0x71, .dst = 0, .src = 5, .off = 0, .imm = 0 },
    .{ .code = 0xbf, .dst = 3, .src = 0, .off = 0, .imm = 0 },
    .{ .code = 0x57, .dst = 3, .src = 0, .off = 0, .imm = 240 },
    .{ .code = 0x55, .dst = 3, .src = 0, .off = 63, .imm = 64 },
    .{ .code = 0x67, .dst = 0, .src = 0, .off = 0, .imm = 2 },
    .{ .code = 0x57, .dst = 0, .src = 0, .off = 0, .imm = 60 },
    .{ .code = 0xb7, .dst = 3, .src = 0, .off = 0, .imm = 20 },
    .{ .code = 0x2d, .dst = 3, .src = 0, .off = 59, .imm = 0 },
    .{ .code = 0xbf, .dst = 3, .src = 5, .off = 0, .imm = 0 },
    .{ .code = 0x0f, .dst = 3, .src = 0, .off = 0, .imm = 0 },
    .{ .code = 0x2d, .dst = 3, .src = 2, .off = 56, .imm = 0 },
    .{ .code = 0x71, .dst = 6, .src = 5, .off = 2, .imm = 0 },
    .{ .code = 0x71, .dst = 4, .src = 5, .off = 3, .imm = 0 },
    .{ .code = 0x67, .dst = 4, .src = 0, .off = 0, .imm = 8 },
    .{ .code = 0x4f, .dst = 4, .src = 6, .off = 0, .imm = 0 },
    .{ .code = 0xdc, .dst = 4, .src = 0, .off = 0, .imm = 16 },
    .{ .code = 0x2d, .dst = 0, .src = 4, .off = 50, .imm = 0 },
    .{ .code = 0x61, .dst = 6, .src = 1, .off = 0, .imm = 0 },
    .{ .code = 0x2d, .dst = 4, .src = 6, .off = 48, .imm = 0 },
    .{ .code = 0x71, .dst = 6, .src = 5, .off = 6, .imm = 0 },
    .{ .code = 0x71, .dst = 7, .src = 5, .off = 7, .imm = 0 },
    .{ .code = 0x67, .dst = 7, .src = 0, .off = 0, .imm = 8 },
    .{ .code = 0x4f, .dst = 7, .src = 6, .off = 0, .imm = 0 },
    .{ .code = 0x57, .dst = 7, .src = 0, .off = 0, .imm = 65343 },
    .{ .code = 0x55, .dst = 7, .src = 0, .off = 42, .imm = 0 },
    .{ .code = 0x1f, .dst = 4, .src = 0, .off = 0, .imm = 0 },
    .{ .code = 0x71, .dst = 5, .src = 5, .off = 9, .imm = 0 },
    .{ .code = 0x15, .dst = 5, .src = 0, .off = 16, .imm = 17 },
    .{ .code = 0x55, .dst = 5, .src = 0, .off = 38, .imm = 6 },
    .{ .code = 0xb7, .dst = 5, .src = 0, .off = 0, .imm = 20 },
    .{ .code = 0x2d, .dst = 5, .src = 4, .off = 36, .imm = 0 },
    .{ .code = 0xbf, .dst = 5, .src = 3, .off = 0, .imm = 0 },
    .{ .code = 0x07, .dst = 5, .src = 0, .off = 0, .imm = 20 },
    .{ .code = 0x2d, .dst = 5, .src = 2, .off = 33, .imm = 0 },
    .{ .code = 0x71, .dst = 5, .src = 3, .off = 12, .imm = 0 },
    .{ .code = 0x77, .dst = 5, .src = 0, .off = 0, .imm = 2 },
    .{ .code = 0x57, .dst = 5, .src = 0, .off = 0, .imm = 60 },
    .{ .code = 0xb7, .dst = 0, .src = 0, .off = 0, .imm = 20 },
    .{ .code = 0x2d, .dst = 0, .src = 5, .off = 28, .imm = 0 },
    .{ .code = 0x2d, .dst = 5, .src = 4, .off = 27, .imm = 0 },
    .{ .code = 0xbf, .dst = 4, .src = 3, .off = 0, .imm = 0 },
    .{ .code = 0x0f, .dst = 4, .src = 5, .off = 0, .imm = 0 },
    .{ .code = 0x2d, .dst = 4, .src = 2, .off = 24, .imm = 0 },
    .{ .code = 0x05, .dst = 0, .src = 0, .off = 13, .imm = 0 },
    .{ .code = 0xb7, .dst = 5, .src = 0, .off = 0, .imm = 8 },
    .{ .code = 0x2d, .dst = 5, .src = 4, .off = 21, .imm = 0 },
    .{ .code = 0xbf, .dst = 5, .src = 3, .off = 0, .imm = 0 },
    .{ .code = 0x07, .dst = 5, .src = 0, .off = 0, .imm = 8 },
    .{ .code = 0x2d, .dst = 5, .src = 2, .off = 18, .imm = 0 },
    .{ .code = 0x71, .dst = 5, .src = 3, .off = 4, .imm = 0 },
    .{ .code = 0x71, .dst = 2, .src = 3, .off = 5, .imm = 0 },
    .{ .code = 0x67, .dst = 2, .src = 0, .off = 0, .imm = 8 },
    .{ .code = 0x4f, .dst = 2, .src = 5, .off = 0, .imm = 0 },
    .{ .code = 0xdc, .dst = 2, .src = 0, .off = 0, .imm = 16 },
    .{ .code = 0xb7, .dst = 5, .src = 0, .off = 0, .imm = 8 },
    .{ .code = 0x2d, .dst = 5, .src = 2, .off = 11, .imm = 0 },
    .{ .code = 0x2d, .dst = 2, .src = 4, .off = 10, .imm = 0 },
    .{ .code = 0x71, .dst = 2, .src = 3, .off = 2, .imm = 0 },
    .{ .code = 0x71, .dst = 3, .src = 3, .off = 3, .imm = 0 },
    .{ .code = 0x67, .dst = 3, .src = 0, .off = 0, .imm = 8 },
    .{ .code = 0x4f, .dst = 3, .src = 2, .off = 0, .imm = 0 },
    .{ .code = 0xdc, .dst = 3, .src = 0, .off = 0, .imm = 16 },
    .{ .code = 0x07, .dst = 3, .src = 0, .off = 0, .imm = -29500 },
    .{ .code = 0x57, .dst = 3, .src = 0, .off = 0, .imm = 65535 },
    .{ .code = 0x25, .dst = 3, .src = 0, .off = 2, .imm = 100 },
    .{ .code = 0xb7, .dst = 2, .src = 0, .off = 0, .imm = 6 },
    .{ .code = 0x63, .dst = 1, .src = 2, .off = 32, .imm = 0 },
    .{ .code = 0xb7, .dst = 0, .src = 0, .off = 0, .imm = 0 },
    .{ .code = 0x95, .dst = 0, .src = 0, .off = 0, .imm = 0 },
};
