// generated by tools/bpf_gen.zig from bpf/lb.c — do not edit
//
// regenerate with:
//   clang -target bpf -O2 -g -c -o lb.o bpf/lb.c
//   zig run tools/bpf_gen.zig -- lb.o src/network/bpf/lb.zig
//
// placeholder: defines map layouts and relocation structure for the
// load balancer. the actual bytecode should be regenerated from the
// C source once clang with BPF target support is available.

const BPF = @import("std").os.linux.BPF;

pub const MapDef = struct {
    name: []const u8,
    map_type: u32,
    key_size: u32,
    value_size: u32,
    max_entries: u32,
};

/// map 0: backends_map — service VIP → backend IP list
/// map 1: conntrack_map — 5-tuple → selected backend IP
/// map 2: rr_counter — single-element array for round-robin
pub const maps = [_]MapDef{
    .{ .name = "backends_map", .map_type = 1, .key_size = 4, .value_size = 68, .max_entries = 256 },
    .{ .name = "conntrack_map", .map_type = 9, .key_size = 16, .value_size = 4, .max_entries = 65536 },
    .{ .name = "rr_counter", .map_type = 2, .key_size = 4, .value_size = 4, .max_entries = 1 },
};

pub const Reloc = struct {
    insn_idx: u32,
    map_idx: u32,
};

// placeholder relocations — the real bytecode will have ld_imm64
// instructions referencing the maps at specific offsets.
pub const relocs = [_]Reloc{
    .{ .insn_idx = 40, .map_idx = 0 }, // backends_map lookup
    .{ .insn_idx = 50, .map_idx = 1 }, // conntrack_map lookup
    .{ .insn_idx = 60, .map_idx = 2 }, // rr_counter lookup
    .{ .insn_idx = 70, .map_idx = 1 }, // conntrack_map update
};

/// BPF program section: "tc_ingress"
pub const prog_name = "tc_ingress";

// placeholder instructions: passes all packets through.
// the real bytecode from clang will be ~200+ instructions with
// the full DNAT logic, conntrack, and round-robin selection.
pub const insns = [_]BPF.Insn{
    .{ .code = 0xb7, .dst = 0, .src = 0, .off = 0, .imm = 0 }, // mov r0, 0 (TC_ACT_OK)
    .{ .code = 0x95, .dst = 0, .src = 0, .off = 0, .imm = 0 }, // exit
};
