// generated by tools/bpf_gen.zig from bpf/policy.c — do not edit
//
// regenerate with:
//   clang -target bpf -O2 -g -c -o policy.o bpf/policy.c
//   zig run tools/bpf_gen.zig -- policy.o src/network/bpf/policy.zig
//
// placeholder: defines the map layout and relocation structure for the
// policy enforcer. the actual bytecode should be regenerated from the
// C source once clang with BPF target support is available.

const BPF = @import("std").os.linux.BPF;

pub const MapDef = struct {
    name: []const u8,
    map_type: u32,
    key_size: u32,
    value_size: u32,
    max_entries: u32,
};

/// map 0: policy_map — (src_ip, dst_ip) pair → action (u8: 0=deny, 1=allow)
/// map 1: isolation_map — src_ip → flag (u8: 1=isolated)
pub const maps = [_]MapDef{
    .{ .name = "policy_map", .map_type = 1, .key_size = 8, .value_size = 1, .max_entries = 4096 },
    .{ .name = "isolation_map", .map_type = 1, .key_size = 4, .value_size = 1, .max_entries = 1024 },
};

pub const Reloc = struct {
    insn_idx: u32,
    map_idx: u32,
};

// placeholder relocations — the real bytecode will have ld_imm64
// instructions referencing policy_map and isolation_map.
pub const relocs = [_]Reloc{
    .{ .insn_idx = 20, .map_idx = 0 }, // policy_map lookup
    .{ .insn_idx = 30, .map_idx = 1 }, // isolation_map lookup
};

/// BPF program section: "tc_ingress"
pub const prog_name = "tc_ingress";

// placeholder instructions: passes all packets through.
// the real bytecode from clang will be ~40-50 instructions with
// ethernet/IP parsing, two map lookups, and conditional drops.
pub const insns = [_]BPF.Insn{
    .{ .code = 0xb7, .dst = 0, .src = 0, .off = 0, .imm = 0 }, // mov r0, 0 (TC_ACT_OK)
    .{ .code = 0x95, .dst = 0, .src = 0, .off = 0, .imm = 0 }, // exit
};
