// generated by tools/bpf_gen.zig — do not edit
//
// regenerate with:
//   clang -target bpf -O2 -g -c -o <name>.o bpf/<name>.c
//   zig run tools/bpf_gen.zig -- <name>.o src/network/bpf/<name>.zig

const BPF = @import("std").os.linux.BPF;

pub const MapDef = struct {
    name: []const u8,
    map_type: u32,
    key_size: u32,
    value_size: u32,
    max_entries: u32,
};

pub const maps = [_]MapDef{
    .{ .name = "port_map", .map_type = 1, .key_size = 8, .value_size = 8, .max_entries = 1024 },
};

pub const Reloc = struct {
    insn_idx: u32,
    map_idx: u32,
};

/// BPF program section: "xdp"
pub const prog_name = "xdp";

pub const relocs = [_]Reloc{};

pub const insns = [_]BPF.Insn{
    .{ .code = 0x61, .dst = 2, .src = 1, .off = 4, .imm = 0 },
    .{ .code = 0x61, .dst = 1, .src = 1, .off = 0, .imm = 0 },
    .{ .code = 0xbf, .dst = 3, .src = 2, .off = 0, .imm = 0 },
    .{ .code = 0x1f, .dst = 3, .src = 1, .off = 0, .imm = 0 },
    .{ .code = 0x67, .dst = 3, .src = 0, .off = 0, .imm = 32 },
    .{ .code = 0x77, .dst = 3, .src = 0, .off = 0, .imm = 32 },
    .{ .code = 0xb7, .dst = 4, .src = 0, .off = 0, .imm = 60 },
    .{ .code = 0x2d, .dst = 4, .src = 3, .off = 23, .imm = 0 },
    .{ .code = 0x25, .dst = 3, .src = 0, .off = 22, .imm = 9000 },
    .{ .code = 0xbf, .dst = 3, .src = 1, .off = 0, .imm = 0 },
    .{ .code = 0x07, .dst = 3, .src = 0, .off = 0, .imm = 14 },
    .{ .code = 0x2d, .dst = 3, .src = 2, .off = 19, .imm = 0 },
    .{ .code = 0x71, .dst = 3, .src = 1, .off = 13, .imm = 0 },
    .{ .code = 0x67, .dst = 3, .src = 0, .off = 0, .imm = 8 },
    .{ .code = 0x71, .dst = 4, .src = 1, .off = 12, .imm = 0 },
    .{ .code = 0x4f, .dst = 3, .src = 4, .off = 0, .imm = 0 },
    .{ .code = 0x55, .dst = 3, .src = 0, .off = 14, .imm = 8 },
    .{ .code = 0xbf, .dst = 3, .src = 1, .off = 0, .imm = 0 },
    .{ .code = 0x07, .dst = 3, .src = 0, .off = 0, .imm = 34 },
    .{ .code = 0x2d, .dst = 3, .src = 2, .off = 11, .imm = 0 },
    .{ .code = 0x71, .dst = 3, .src = 1, .off = 16, .imm = 0 },
    .{ .code = 0x71, .dst = 2, .src = 1, .off = 17, .imm = 0 },
    .{ .code = 0x67, .dst = 2, .src = 0, .off = 0, .imm = 8 },
    .{ .code = 0x4f, .dst = 2, .src = 3, .off = 0, .imm = 0 },
    .{ .code = 0xdc, .dst = 2, .src = 0, .off = 0, .imm = 16 },
    .{ .code = 0xb7, .dst = 3, .src = 0, .off = 0, .imm = 40 },
    .{ .code = 0x2d, .dst = 3, .src = 2, .off = 4, .imm = 0 },
    .{ .code = 0x25, .dst = 2, .src = 0, .off = 3, .imm = 9000 },
    .{ .code = 0x71, .dst = 1, .src = 1, .off = 22, .imm = 0 },
    .{ .code = 0x15, .dst = 1, .src = 0, .off = 1, .imm = 0 },
    .{ .code = 0x25, .dst = 1, .src = 0, .off = 0, .imm = 128 },
    .{ .code = 0xb7, .dst = 0, .src = 0, .off = 0, .imm = 2 },
    .{ .code = 0x95, .dst = 0, .src = 0, .off = 0, .imm = 0 },
};
