// generated by tools/bpf_gen.zig — do not edit
//
// regenerate with:
//   clang -target bpf -O2 -g -c -o <name>.o bpf/<name>.c
//   zig run tools/bpf_gen.zig -- <name>.o src/network/bpf/<name>.zig

const BPF = @import("std").os.linux.BPF;

pub const MapDef = struct {
    name: []const u8,
    map_type: u32,
    key_size: u32,
    value_size: u32,
    max_entries: u32,
};

pub const maps = [_]MapDef{
    .{ .name = "storage_metrics_map", .map_type = 9, .key_size = 8, .value_size = 32, .max_entries = 1024 },
};

pub const Reloc = struct {
    insn_idx: u32,
    map_idx: u32,
};

/// BPF program section: "tracepoint/block/block_rq_complete"
pub const prog_name = "tracepoint/block/block_rq_complete";

pub const relocs = [_]Reloc{
    .{ .insn_idx = 12, .map_idx = 0 },
    .{ .insn_idx = 44, .map_idx = 0 },
};

pub const insns = [_]BPF.Insn{
    .{ .code = 0xbf, .dst = 6, .src = 1, .off = 0, .imm = 0 },
    .{ .code = 0x85, .dst = 0, .src = 0, .off = 0, .imm = 80 },
    .{ .code = 0x7b, .dst = 10, .src = 0, .off = -8, .imm = 0 },
    .{ .code = 0x15, .dst = 0, .src = 0, .off = 44, .imm = 0 },
    .{ .code = 0x71, .dst = 7, .src = 6, .off = 32, .imm = 0 },
    .{ .code = 0x15, .dst = 7, .src = 0, .off = 1, .imm = 87 },
    .{ .code = 0x55, .dst = 7, .src = 0, .off = 41, .imm = 82 },
    .{ .code = 0x61, .dst = 6, .src = 6, .off = 24, .imm = 0 },
    .{ .code = 0x25, .dst = 6, .src = 0, .off = 39, .imm = 2097152 },
    .{ .code = 0x67, .dst = 6, .src = 0, .off = 0, .imm = 9 },
    .{ .code = 0xbf, .dst = 2, .src = 10, .off = 0, .imm = 0 },
    .{ .code = 0x07, .dst = 2, .src = 0, .off = 0, .imm = -8 },
    .{ .code = 0x18, .dst = 1, .src = 0, .off = 0, .imm = 0 },
    .{ .code = 0x00, .dst = 0, .src = 0, .off = 0, .imm = 0 },
    .{ .code = 0x85, .dst = 0, .src = 0, .off = 0, .imm = 1 },
    .{ .code = 0x15, .dst = 0, .src = 0, .off = 5, .imm = 0 },
    .{ .code = 0x55, .dst = 7, .src = 0, .off = 14, .imm = 82 },
    .{ .code = 0xdb, .dst = 0, .src = 6, .off = 0, .imm = 0 },
    .{ .code = 0xb7, .dst = 1, .src = 0, .off = 0, .imm = 1 },
    .{ .code = 0xdb, .dst = 0, .src = 1, .off = 16, .imm = 0 },
    .{ .code = 0x05, .dst = 0, .src = 0, .off = 27, .imm = 0 },
    .{ .code = 0xb7, .dst = 1, .src = 0, .off = 0, .imm = 0 },
    .{ .code = 0x7b, .dst = 10, .src = 1, .off = -16, .imm = 0 },
    .{ .code = 0x7b, .dst = 10, .src = 1, .off = -24, .imm = 0 },
    .{ .code = 0x7b, .dst = 10, .src = 1, .off = -32, .imm = 0 },
    .{ .code = 0x7b, .dst = 10, .src = 1, .off = -40, .imm = 0 },
    .{ .code = 0x55, .dst = 7, .src = 0, .off = 8, .imm = 82 },
    .{ .code = 0xbf, .dst = 1, .src = 10, .off = 0, .imm = 0 },
    .{ .code = 0x07, .dst = 1, .src = 0, .off = 0, .imm = -24 },
    .{ .code = 0x7b, .dst = 10, .src = 6, .off = -40, .imm = 0 },
    .{ .code = 0x05, .dst = 0, .src = 0, .off = 7, .imm = 0 },
    .{ .code = 0xdb, .dst = 0, .src = 6, .off = 8, .imm = 0 },
    .{ .code = 0xb7, .dst = 1, .src = 0, .off = 0, .imm = 1 },
    .{ .code = 0xdb, .dst = 0, .src = 1, .off = 24, .imm = 0 },
    .{ .code = 0x05, .dst = 0, .src = 0, .off = 13, .imm = 0 },
    .{ .code = 0xbf, .dst = 1, .src = 10, .off = 0, .imm = 0 },
    .{ .code = 0x07, .dst = 1, .src = 0, .off = 0, .imm = -16 },
    .{ .code = 0x7b, .dst = 10, .src = 6, .off = -32, .imm = 0 },
    .{ .code = 0xb7, .dst = 2, .src = 0, .off = 0, .imm = 1 },
    .{ .code = 0x7b, .dst = 1, .src = 2, .off = 0, .imm = 0 },
    .{ .code = 0xbf, .dst = 2, .src = 10, .off = 0, .imm = 0 },
    .{ .code = 0x07, .dst = 2, .src = 0, .off = 0, .imm = -8 },
    .{ .code = 0xbf, .dst = 3, .src = 10, .off = 0, .imm = 0 },
    .{ .code = 0x07, .dst = 3, .src = 0, .off = 0, .imm = -40 },
    .{ .code = 0x18, .dst = 1, .src = 0, .off = 0, .imm = 0 },
    .{ .code = 0x00, .dst = 0, .src = 0, .off = 0, .imm = 0 },
    .{ .code = 0xb7, .dst = 4, .src = 0, .off = 0, .imm = 0 },
    .{ .code = 0x85, .dst = 0, .src = 0, .off = 0, .imm = 2 },
    .{ .code = 0xb7, .dst = 0, .src = 0, .off = 0, .imm = 0 },
    .{ .code = 0x95, .dst = 0, .src = 0, .off = 0, .imm = 0 },
};
