// generated by tools/bpf_gen.zig from bpf/test_prog.c — do not edit
//
// regenerate with:
//   clang -target bpf -O2 -g -c -o test_prog.o bpf/test_prog.c
//   zig run tools/bpf_gen.zig -- test_prog.o src/network/bpf/test_prog.zig

const BPF = @import("std").os.linux.BPF;

pub const MapDef = struct {
    name: []const u8,
    map_type: u32,
    key_size: u32,
    value_size: u32,
    max_entries: u32,
};

pub const maps = [_]MapDef{};

pub const Reloc = struct {
    insn_idx: u32,
    map_idx: u32,
};

pub const relocs = [_]Reloc{};

/// BPF program section: "tc_ingress"
pub const prog_name = "tc_ingress";

pub const insns = [_]BPF.Insn{
    .{ .code = 0xb7, .dst = 0, .src = 0, .off = 0, .imm = 0 }, // mov r0, 0 (TC_ACT_OK)
    .{ .code = 0x95, .dst = 0, .src = 0, .off = 0, .imm = 0 }, // exit
};
