// ebpf — BPF program loading and TC attachment
//
// loads BPF programs from comptime bytecode arrays (generated by
// tools/bpf_gen.zig), creates maps, patches relocations, and attaches
// programs to network interfaces via TC (traffic control).
//
// uses the zig stdlib's std.os.linux.BPF wrappers — no libbpf dependency.
// the kernel does all the heavy lifting; we just set up the right
// syscall arguments.
//
// lifecycle:
//   1. createMap() for each map definition
//   2. loadProgram() — copies insns, patches map fd relocations, prog_load()
//   3. attachTC() — creates clsact qdisc + adds BPF filter
//   4. detachTC() — removes the filter
//
// all BPF resources (maps, programs) are file descriptors that get
// cleaned up when the yoq process exits.

const std = @import("std");
const builtin = @import("builtin");
const posix = std.posix;
const linux = std.os.linux;
const BPF = linux.BPF;
const log = @import("../lib/log.zig");
const attach_support = @import("ebpf/attach_support.zig");
const common = @import("ebpf/common.zig");
const dns_runtime = @import("ebpf/dns_runtime.zig");
const lb_runtime = @import("ebpf/lb_runtime.zig");
const map_support = @import("ebpf/map_support.zig");
const metrics_runtime = @import("ebpf/metrics_runtime.zig");
const port_map_runtime = @import("ebpf/port_map_runtime.zig");
const policy_runtime = @import("ebpf/policy_runtime.zig");
const program_support = @import("ebpf/program_support.zig");
const resource_support = @import("ebpf/resource_support.zig");
const dns_intercept = @import("bpf/dns_intercept.zig");
const lb_prog = @import("bpf/lb.zig");
const metrics_prog = @import("bpf/metrics.zig");
const port_map_prog = @import("bpf/port_map.zig");
const policy_prog = @import("bpf/policy.zig");

pub const EbpfError = common.EbpfError;
pub const Direction = common.Direction;

// -- map operations --

/// create a BPF map and return its file descriptor.
pub fn createMap(
    map_type: BPF.MapType,
    key_size: u32,
    value_size: u32,
    max_entries: u32,
) EbpfError!posix.fd_t {
    return map_support.createMap(map_type, key_size, value_size, max_entries);
}

/// look up a value in a BPF map by key.
/// returns true if found (value is written to the output buffer).
/// validates that key and value buffers are within acceptable size limits.
pub fn mapLookup(map_fd: posix.fd_t, key: []const u8, value: []u8) bool {
    return map_support.mapLookup(map_fd, key, value);
}

/// get the next key in a BPF map (for iteration).
/// returns true if a next key was found.
/// validates key buffer size for safety.
pub fn mapGetNextKey(map_fd: posix.fd_t, key: []const u8, next_key: []u8) bool {
    return map_support.mapGetNextKey(map_fd, key, next_key);
}

/// insert or update a key/value pair in a BPF map.
/// validates key and value buffer sizes before attempting update.
/// uses circuit breaker pattern to prevent cascading failures.
/// returns MapFull if the map has reached max_entries (for non-LRU maps).
pub fn mapUpdate(map_fd: posix.fd_t, key: []const u8, value: []const u8) EbpfError!void {
    try map_support.mapUpdate(map_fd, key, value);
}

/// delete a key from a BPF map.
/// validates key size before attempting deletion.
/// returns true if the key was found and deleted, false otherwise.
pub fn mapDelete(map_fd: posix.fd_t, key: []const u8) bool {
    return map_support.mapDelete(map_fd, key);
}

// -- program loading --

/// load a BPF program from comptime instruction and relocation arrays.
///
/// creates maps from the provided definitions, copies instructions into
/// a mutable buffer, patches ld_imm64 relocations with map file descriptors,
/// and calls prog_load.
///
/// returns the program fd and map fds. caller owns all fds.
pub fn loadProgram(
    comptime prog: type,
    map_fds: []posix.fd_t,
) EbpfError!posix.fd_t {
    return program_support.loadProgram(prog, map_fds);
}

/// load a BPF program with a specific program type.
///
/// like loadProgram but allows specifying the BPF program type
/// (e.g. .xdp instead of the default .sched_cls).
pub fn loadProgramWithType(
    comptime prog: type,
    map_fds: []posix.fd_t,
    prog_type: BPF.ProgType,
) EbpfError!posix.fd_t {
    return program_support.loadProgramWithType(prog, map_fds, prog_type);
}

/// load an egress BPF program from a module with egress_insns/egress_relocs.
fn loadEgressProgram(
    comptime prog: type,
    map_fds: []posix.fd_t,
) EbpfError!posix.fd_t {
    return program_support.loadEgressProgram(prog, map_fds);
}

/// patch a ld_imm64 instruction to reference a map fd.
///
/// ld_imm64 is a two-instruction wide load. the map fd goes in the
/// first instruction's imm field, and src_reg is set to PSEUDO_MAP_FD
/// to tell the verifier this references a map.
fn patchMapFd(insn: *BPF.Insn, fd: posix.fd_t) void {
    program_support.patchMapFd(insn, fd);
}

// -- TC attachment --

pub fn attachTC(if_index: u32, direction: Direction, prog_fd: posix.fd_t, priority: u32) EbpfError!void {
    try attach_support.attachTC(if_index, direction, prog_fd, priority);
}

/// detach all TC filters from an interface direction.
///
/// removes the clsact qdisc entirely, which removes all attached
/// programs (both ingress and egress). this is the simplest cleanup.
pub fn detachTC(if_index: u32) EbpfError!void {
    try attach_support.detachTC(if_index);
}

// -- DNS interceptor --
//
// convenience functions for loading and managing the DNS interception
// BPF program. the program intercepts DNS A record queries on the
// bridge interface and resolves known service names in-kernel.

pub const DnsInterceptor = dns_runtime.DnsInterceptor;

fn makeKey(name: []const u8) ?[64]u8 {
    return dns_runtime.makeKey(name);
}

/// guards access to all global BPF state (dns_interceptor, load_balancer,
/// metrics_collector, policy_enforcer). currently safe because container
/// startup is sequential, but this protects against future parallel
/// startup (e.g. `yoq up` with multiple services).
var global_mutex: @import("compat").Mutex = .{};
fn trackBpfFdClosed() void {
    resource_support.releaseBpfFd();
}

/// global DNS interceptor instance. set after loadDnsInterceptor() succeeds.
var dns_interceptor: ?DnsInterceptor = null;

/// load and attach the DNS interception BPF program to the bridge.
///
/// creates the service_names map, loads the program, and attaches it
/// as a TC ingress filter on the given bridge interface. idempotent —
/// returns immediately if already loaded.
pub fn loadDnsInterceptor(bridge_if_index: u32) EbpfError!void {
    global_mutex.lock();
    defer global_mutex.unlock();

    if (dns_interceptor != null) return; // already loaded
    dns_interceptor = try dns_runtime.load(bridge_if_index);

    log.info("ebpf: DNS interceptor loaded on ifindex {d}", .{bridge_if_index});
}

/// unload the DNS interceptor. detaches from TC and closes fds.
pub fn unloadDnsInterceptor() void {
    global_mutex.lock();
    defer global_mutex.unlock();

    if (dns_interceptor) |*interceptor| {
        interceptor.deinit();
        dns_interceptor = null;
        log.info("ebpf: DNS interceptor unloaded", .{});
    }
}

/// get the active DNS interceptor, if loaded.
pub fn getDnsInterceptor() ?*const DnsInterceptor {
    global_mutex.lock();
    defer global_mutex.unlock();

    if (dns_interceptor) |*interceptor| {
        return interceptor;
    }
    return null;
}

// -- load balancer --
//
// round-robin load balancing across multiple backends for a service.
// the backends_map stores service VIP → backend IP list. when a
// service has multiple containers, connections are distributed
// across them via atomic round-robin with connection affinity.

pub const max_backends = lb_runtime.max_backends;
pub const ServiceBackends = lb_runtime.ServiceBackends;
pub const LoadBalancer = lb_runtime.LoadBalancer;

/// global load balancer instance.
var load_balancer: ?LoadBalancer = null;

/// load and attach the load balancer BPF program.
pub fn loadLoadBalancer(bridge_if_index: u32) EbpfError!void {
    global_mutex.lock();
    defer global_mutex.unlock();

    if (load_balancer != null) return;
    load_balancer = try lb_runtime.load(bridge_if_index);

    log.info("ebpf: load balancer loaded on ifindex {d}", .{bridge_if_index});
}

/// unload the load balancer.
pub fn unloadLoadBalancer() void {
    global_mutex.lock();
    defer global_mutex.unlock();

    if (load_balancer) |*lb| {
        lb.deinit();
        load_balancer = null;
        log.info("ebpf: load balancer unloaded", .{});
    }
}

/// get the active load balancer, if loaded.
pub fn getLoadBalancer() ?*const LoadBalancer {
    global_mutex.lock();
    defer global_mutex.unlock();

    if (load_balancer) |*lb| {
        return lb;
    }
    return null;
}

/// convert a 4-byte IP to a u32 in network byte order.
/// the bytes are already in network order — this is just a type pun.
pub fn ipToNetworkOrder(ip_bytes: [4]u8) u32 {
    return lb_runtime.ipToNetworkOrder(ip_bytes);
}

// -- metrics collector --
//
// per-IP packet and byte counting via an LRU hash map. attached to the
// bridge ingress at priority 2 (after DNS and LB). purely passive —
// never drops packets.
//
// userspace reads the map to report per-container network traffic
// via `yoq metrics`.

pub const IpMetrics = metrics_runtime.IpMetrics;
pub const PairKey = metrics_runtime.PairKey;
pub const PairMetrics = metrics_runtime.PairMetrics;
pub const MetricsCollector = metrics_runtime.MetricsCollector;
pub const PairEntry = metrics_runtime.PairEntry;

/// global metrics collector instance.
var metrics_collector: ?MetricsCollector = null;

/// load and attach the metrics BPF program to the bridge.
pub fn loadMetricsCollector(bridge_if_index: u32) EbpfError!void {
    global_mutex.lock();
    defer global_mutex.unlock();

    if (metrics_collector != null) return;
    metrics_collector = try metrics_runtime.load(bridge_if_index);

    log.info("ebpf: metrics collector loaded on ifindex {d}", .{bridge_if_index});
}

/// unload the metrics collector.
pub fn unloadMetricsCollector() void {
    global_mutex.lock();
    defer global_mutex.unlock();

    if (metrics_collector) |*mc| {
        mc.deinit();
        metrics_collector = null;
        log.info("ebpf: metrics collector unloaded", .{});
    }
}

/// get the active metrics collector, if loaded.
pub fn getMetricsCollector() ?*const MetricsCollector {
    global_mutex.lock();
    defer global_mutex.unlock();

    if (metrics_collector) |*mc| {
        return mc;
    }
    return null;
}

// -- policy enforcer --
//
// per-IP-pair allow/deny enforcement. attached to the bridge ingress
// at priority 0 (before DNS, LB, and metrics). drops packets matching
// deny rules or packets from isolated sources without an allow entry.

pub const PolicyKey = policy_runtime.PolicyKey;
pub const PolicyEnforcer = policy_runtime.PolicyEnforcer;

/// global policy enforcer instance.
var policy_enforcer: ?PolicyEnforcer = null;

/// load and attach the policy enforcer BPF program to the bridge.
/// attaches at priority 0 (runs before DNS/LB at 1 and metrics at 2).
pub fn loadPolicyEnforcer(bridge_if_index: u32) EbpfError!void {
    global_mutex.lock();
    defer global_mutex.unlock();

    if (policy_enforcer != null) return;
    policy_enforcer = try policy_runtime.load(bridge_if_index);

    log.info("ebpf: policy enforcer loaded on ifindex {d}", .{bridge_if_index});
}

/// unload the policy enforcer.
pub fn unloadPolicyEnforcer() void {
    global_mutex.lock();
    defer global_mutex.unlock();

    if (policy_enforcer) |*pe| {
        pe.deinit();
        policy_enforcer = null;
        log.info("ebpf: policy enforcer unloaded", .{});
    }
}

/// get the active policy enforcer, if loaded.
pub fn getPolicyEnforcer() ?*const PolicyEnforcer {
    global_mutex.lock();
    defer global_mutex.unlock();

    if (policy_enforcer) |*pe| {
        return pe;
    }
    return null;
}

// -- XDP port mapper --
//
// XDP-based port mapping for fast container port forwarding.
// rewrites destination IP and port for inbound traffic, replacing
// iptables DNAT rules. uses SKB mode for compatibility with
// virtual interfaces (bridges, veths).
//
// falls back to iptables if XDP isn't available (old kernel,
// no CAP_BPF, or interface doesn't support XDP).

pub const PortKey = port_map_runtime.PortKey;
pub const PortTarget = port_map_runtime.PortTarget;
pub const PortMapper = port_map_runtime.PortMapper;

var port_mapper: ?PortMapper = null;

/// load and attach the XDP port mapping program to an interface.
pub fn loadPortMapper(if_index: u32) EbpfError!void {
    global_mutex.lock();
    defer global_mutex.unlock();

    if (port_mapper != null) return;
    port_mapper = try port_map_runtime.load(if_index);

    log.info("ebpf: port mapper loaded on ifindex {d}", .{if_index});
}

pub fn unloadPortMapper() void {
    global_mutex.lock();
    defer global_mutex.unlock();

    if (port_mapper) |*pm| {
        pm.deinit();
        port_mapper = null;
        log.info("ebpf: port mapper unloaded", .{});
    }
}

pub fn getPortMapper() ?*const PortMapper {
    global_mutex.lock();
    defer global_mutex.unlock();

    if (port_mapper) |*pm| {
        return pm;
    }
    return null;
}

// -- XDP attach/detach --

/// attach an XDP program to an interface using SKB mode.
/// SKB mode (generic XDP) works on all interface types including
/// virtual ones like bridges and veths.
pub fn attachXdp(if_index: u32, prog_fd: posix.fd_t) EbpfError!void {
    try attach_support.attachXdp(if_index, prog_fd);
}

/// detach XDP program from an interface.
pub fn detachXdp(if_index: u32) EbpfError!void {
    try attach_support.detachXdp(if_index);
}

// -- capability check --

/// check if BPF is supported on this system.
///
/// tries to create a minimal hash map — if it fails (typically EPERM
/// or ENOSYS), BPF is not available. the test map is immediately closed.
pub fn isSupported() bool {
    if (comptime builtin.os.tag != .linux) return false;

    const fd = BPF.map_create(.hash, 4, 4, 1) catch return false;
    @import("compat").posix.close(fd);
    return true;
}

// -- tests --

test "patchMapFd sets src_reg and imm" {
    var insn = BPF.Insn{
        .code = BPF.LD | BPF.IMM | BPF.DW,
        .dst = 0,
        .src = 0,
        .off = 0,
        .imm = 0,
    };

    patchMapFd(&insn, 42);
    try std.testing.expectEqual(@as(u4, BPF.PSEUDO_MAP_FD), insn.src);
    try std.testing.expectEqual(@as(i32, 42), insn.imm);
}

test "patchMapFd with negative fd value" {
    // fds should always be positive, but test the mechanics
    var insn = BPF.Insn{
        .code = BPF.LD | BPF.IMM | BPF.DW,
        .dst = 0,
        .src = 0,
        .off = 0,
        .imm = 0,
    };

    patchMapFd(&insn, 7);
    try std.testing.expectEqual(@as(i32, 7), insn.imm);
    try std.testing.expectEqual(@as(u4, BPF.PSEUDO_MAP_FD), insn.src);
}

test "direction enum" {
    // verify the direction enum works as expected
    try std.testing.expectEqual(Direction.ingress, Direction.ingress);
    try std.testing.expect(Direction.ingress != Direction.egress);
}

test "isSupported returns a boolean" {
    // we can't guarantee BPF is available in CI, but we can verify
    // the function doesn't crash and returns a valid bool
    const result = isSupported();
    try std.testing.expect(result == true or result == false);
}

test "makeKey produces wire-format DNS name" {
    // "mydb" → "\x04mydb\x00" + zero padding
    const key = makeKey("mydb").?;
    try std.testing.expectEqual(@as(u8, 4), key[0]); // label length
    try std.testing.expectEqualStrings("mydb", key[1..5]);
    try std.testing.expectEqual(@as(u8, 0), key[5]); // null terminator
    try std.testing.expectEqual(@as(u8, 0), key[63]);
}

test "makeKey handles dotted names" {
    // "web.db" → "\x03web\x02db\x00"
    const key = makeKey("web.db").?;
    try std.testing.expectEqual(@as(u8, 3), key[0]);
    try std.testing.expectEqualStrings("web", key[1..4]);
    try std.testing.expectEqual(@as(u8, 2), key[4]);
    try std.testing.expectEqualStrings("db", key[5..7]);
    try std.testing.expectEqual(@as(u8, 0), key[7]);
}

test "makeKey rejects invalid names" {
    try std.testing.expect(makeKey("") == null);
    try std.testing.expect(makeKey(".foo") == null); // empty label
    try std.testing.expect(makeKey("foo.") == null); // trailing dot = empty label
}

test "dns_intercept bytecode has expected structure" {
    // verify the generated bytecode module has the expected fields
    try std.testing.expectEqual(@as(usize, 1), dns_intercept.maps.len);
    try std.testing.expectEqualStrings("service_names", dns_intercept.maps[0].name);
    try std.testing.expectEqual(@as(u32, 64), dns_intercept.maps[0].key_size);
    try std.testing.expectEqual(@as(u32, 4), dns_intercept.maps[0].value_size);
    try std.testing.expect(dns_intercept.insns.len >= 2);
}

test "ipToNetworkOrder converts correctly" {
    // 10.42.0.5 → bytes in memory order
    const ip = [4]u8{ 10, 42, 0, 5 };
    const net = ipToNetworkOrder(ip);
    // in network byte order (big-endian), 10.42.0.5 = 0x0A2A0005
    // but ipToNetworkOrder stores it as-is in memory layout for BPF:
    // byte[0]=10 at lowest address
    const bytes = std.mem.asBytes(&net);
    try std.testing.expectEqual(@as(u8, 10), bytes[0]);
    try std.testing.expectEqual(@as(u8, 42), bytes[1]);
    try std.testing.expectEqual(@as(u8, 0), bytes[2]);
    try std.testing.expectEqual(@as(u8, 5), bytes[3]);
}

test "ServiceBackends struct size matches BPF map value" {
    // must match lb.c: struct service_backends
    // count (4) + ips[64] (256) = 260 bytes
    try std.testing.expectEqual(@as(usize, 260), @sizeOf(ServiceBackends));
    try std.testing.expectEqual(@as(u32, 260), lb_prog.maps[0].value_size);
}

test "lb_prog bytecode has expected maps" {
    try std.testing.expectEqual(@as(usize, 3), lb_prog.maps.len);
    try std.testing.expectEqualStrings("backends_map", lb_prog.maps[0].name);
    try std.testing.expectEqualStrings("conntrack_map", lb_prog.maps[1].name);
    try std.testing.expectEqualStrings("rev_conntrack_map", lb_prog.maps[2].name);
}

test "IpMetrics struct size matches BPF map value" {
    // must match metrics.c: struct ip_metrics
    // packets (8) + bytes (8) = 16 bytes
    try std.testing.expectEqual(@as(usize, 16), @sizeOf(IpMetrics));
    try std.testing.expectEqual(@as(u32, 16), metrics_prog.maps[0].value_size);
}

test "PairKey struct size matches BPF map key" {
    // must match metrics.c: struct pair_key
    // src_ip (4) + dst_ip (4) + dst_port (2) + pad (2) = 12 bytes
    try std.testing.expectEqual(@as(usize, 12), @sizeOf(PairKey));
    try std.testing.expectEqual(@as(u32, 12), metrics_prog.maps[1].key_size);
}

test "PairMetrics struct size matches BPF map value" {
    // must match metrics.c: struct pair_metrics
    // packets (8) + bytes (8) + connections (8) + errors (8) = 32 bytes
    try std.testing.expectEqual(@as(usize, 32), @sizeOf(PairMetrics));
    try std.testing.expectEqual(@as(u32, 32), metrics_prog.maps[1].value_size);
}

test "metrics_prog bytecode has expected structure" {
    try std.testing.expectEqual(@as(usize, 2), metrics_prog.maps.len);
    try std.testing.expectEqualStrings("metrics_map", metrics_prog.maps[0].name);
    try std.testing.expectEqualStrings("pair_metrics_map", metrics_prog.maps[1].name);
    // LRU_HASH = 9
    try std.testing.expectEqual(@as(u32, 9), metrics_prog.maps[0].map_type);
    try std.testing.expectEqual(@as(u32, 9), metrics_prog.maps[1].map_type);
    try std.testing.expectEqual(@as(u32, 4), metrics_prog.maps[0].key_size);
    try std.testing.expect(metrics_prog.insns.len >= 2);
}

test "PolicyKey struct size matches BPF map key" {
    // must match policy.c: struct policy_key
    // src_ip (4) + dst_ip (4) = 8 bytes
    try std.testing.expectEqual(@as(usize, 8), @sizeOf(PolicyKey));
    try std.testing.expectEqual(@as(u32, 8), policy_prog.maps[0].key_size);
}

test "policy_prog bytecode has expected maps" {
    try std.testing.expectEqual(@as(usize, 2), policy_prog.maps.len);
    try std.testing.expectEqualStrings("policy_map", policy_prog.maps[0].name);
    try std.testing.expectEqualStrings("isolation_map", policy_prog.maps[1].name);
    // HASH = 1
    try std.testing.expectEqual(@as(u32, 1), policy_prog.maps[0].map_type);
    try std.testing.expectEqual(@as(u32, 1), policy_prog.maps[1].map_type);
    // isolation_map: key=4 (u32 IP), value=1 (u8 flag)
    try std.testing.expectEqual(@as(u32, 4), policy_prog.maps[1].key_size);
    try std.testing.expectEqual(@as(u32, 1), policy_prog.maps[1].value_size);
    try std.testing.expect(policy_prog.insns.len >= 2);
}

test "createMap returns fd or error" {
    // try creating a map — may fail without CAP_BPF
    const result = createMap(.hash, 4, 4, 16);
    if (result) |fd| {
        try std.testing.expect(fd >= 0);
        @import("compat").posix.close(fd);
    } else |_| {
        // expected in unprivileged environments
    }
}

test "PortKey struct size matches BPF map key" {
    try std.testing.expectEqual(@as(usize, 8), @sizeOf(PortKey));
    try std.testing.expectEqual(@as(u32, 8), port_map_prog.maps[0].key_size);
}

test "PortTarget struct size matches BPF map value" {
    try std.testing.expectEqual(@as(usize, 8), @sizeOf(PortTarget));
    try std.testing.expectEqual(@as(u32, 8), port_map_prog.maps[0].value_size);
}

test "port_map_prog bytecode has expected structure" {
    try std.testing.expectEqual(@as(usize, 1), port_map_prog.maps.len);
    try std.testing.expectEqualStrings("port_map", port_map_prog.maps[0].name);
    try std.testing.expectEqual(@as(u32, 1), port_map_prog.maps[0].map_type); // HASH
    try std.testing.expect(port_map_prog.insns.len >= 2);
}
