// ebpf — BPF program loading and TC attachment
//
// loads BPF programs from comptime bytecode arrays (generated by
// tools/bpf_gen.zig), creates maps, patches relocations, and attaches
// programs to network interfaces via TC (traffic control).
//
// uses the zig stdlib's std.os.linux.BPF wrappers — no libbpf dependency.
// the kernel does all the heavy lifting; we just set up the right
// syscall arguments.
//
// lifecycle:
//   1. createMap() for each map definition
//   2. loadProgram() — copies insns, patches map fd relocations, prog_load()
//   3. attachTC() — creates clsact qdisc + adds BPF filter
//   4. detachTC() — removes the filter
//
// all BPF resources (maps, programs) are file descriptors that get
// cleaned up when the yoq process exits.

const std = @import("std");
const posix = std.posix;
const linux = std.os.linux;
const BPF = linux.BPF;
const nl = @import("netlink.zig");
const log = @import("../lib/log.zig");

pub const EbpfError = error{
    MapCreateFailed,
    ProgramLoadFailed,
    AttachFailed,
    DetachFailed,
    NotSupported,
};

/// direction for TC program attachment
pub const Direction = enum {
    ingress,
    egress,
};

// -- map operations --

/// create a BPF map and return its file descriptor.
pub fn createMap(
    map_type: BPF.MapType,
    key_size: u32,
    value_size: u32,
    max_entries: u32,
) EbpfError!posix.fd_t {
    const fd = BPF.map_create(map_type, key_size, value_size, max_entries) catch |e| {
        log.warn("ebpf: map_create failed (type={d}, key={d}, val={d}): {}", .{
            @intFromEnum(map_type), key_size, value_size, e,
        });
        return EbpfError.MapCreateFailed;
    };
    return fd;
}

/// look up a value in a BPF map by key.
/// returns true if found (value is written to the output buffer).
pub fn mapLookup(map_fd: posix.fd_t, key: []const u8, value: []u8) bool {
    BPF.map_lookup_elem(map_fd, key, value) catch return false;
    return true;
}

/// insert or update a key/value pair in a BPF map.
pub fn mapUpdate(map_fd: posix.fd_t, key: []const u8, value: []const u8) EbpfError!void {
    BPF.map_update_elem(map_fd, key, value, BPF.ANY) catch |e| {
        log.warn("ebpf: map_update failed: {}", .{e});
        return EbpfError.MapCreateFailed;
    };
}

/// delete a key from a BPF map.
pub fn mapDelete(map_fd: posix.fd_t, key: []const u8) void {
    BPF.map_delete_elem(map_fd, key) catch {};
}

// -- program loading --

/// maximum number of BPF instructions we support in a single program.
/// the kernel limit is 1M for privileged programs, but our programs
/// are much smaller than this.
const max_insns = 4096;

/// maximum number of maps a single program can reference.
const max_maps = 16;

/// load a BPF program from comptime instruction and relocation arrays.
///
/// creates maps from the provided definitions, copies instructions into
/// a mutable buffer, patches ld_imm64 relocations with map file descriptors,
/// and calls prog_load.
///
/// returns the program fd and map fds. caller owns all fds.
pub fn loadProgram(
    comptime prog: type,
    map_fds: []posix.fd_t,
) EbpfError!posix.fd_t {
    const insns = prog.insns;
    const relocs = prog.relocs;
    const maps = prog.maps;

    if (insns.len == 0) return EbpfError.ProgramLoadFailed;
    if (insns.len > max_insns) return EbpfError.ProgramLoadFailed;

    // copy instructions into a mutable buffer for patching
    var mutable_insns: [insns.len]BPF.Insn = insns;

    // patch relocations: set map fd in ld_imm64 instructions
    for (relocs) |reloc| {
        if (reloc.insn_idx >= insns.len) continue;
        if (reloc.map_idx >= maps.len) continue;

        const fd = map_fds[reloc.map_idx];
        patchMapFd(&mutable_insns[reloc.insn_idx], fd);
    }

    // load the program
    var log_buf: [4096]u8 = undefined;
    var bpf_log = BPF.Log{
        .level = 1,
        .buf = &log_buf,
    };

    const prog_fd = BPF.prog_load(
        .sched_cls,
        &mutable_insns,
        &bpf_log,
        "GPL",
        0,
        0,
    ) catch |e| {
        // log the verifier output for debugging
        const log_end = std.mem.indexOfScalar(u8, &log_buf, 0) orelse log_buf.len;
        if (log_end > 0) {
            log.warn("ebpf: verifier output: {s}", .{log_buf[0..log_end]});
        }
        log.warn("ebpf: prog_load failed: {}", .{e});
        return EbpfError.ProgramLoadFailed;
    };

    return prog_fd;
}

/// patch a ld_imm64 instruction to reference a map fd.
///
/// ld_imm64 is a two-instruction wide load. the map fd goes in the
/// first instruction's imm field, and src_reg is set to PSEUDO_MAP_FD
/// to tell the verifier this references a map.
fn patchMapFd(insn: *BPF.Insn, fd: posix.fd_t) void {
    insn.src = BPF.PSEUDO_MAP_FD;
    insn.imm = @intCast(fd);
}

// -- TC attachment --

/// attach a BPF program to a network interface via TC.
///
/// 1. creates a clsact qdisc on the interface (idempotent — ignores
///    EEXIST so it's safe to call multiple times)
/// 2. adds the BPF program as a TC filter on the specified direction
pub fn attachTC(if_index: u32, direction: Direction, prog_fd: posix.fd_t) EbpfError!void {
    const fd = nl.openSocket() catch return EbpfError.AttachFailed;
    defer posix.close(fd);

    // step 1: create clsact qdisc (idempotent)
    createClsactQdisc(fd, if_index) catch |e| {
        log.warn("ebpf: failed to create clsact qdisc on ifindex {d}: {}", .{ if_index, e });
        return EbpfError.AttachFailed;
    };

    // step 2: add BPF filter
    addBpfFilter(fd, if_index, direction, prog_fd) catch |e| {
        log.warn("ebpf: failed to add BPF filter on ifindex {d}: {}", .{ if_index, e });
        return EbpfError.AttachFailed;
    };
}

/// detach all TC filters from an interface direction.
///
/// removes the clsact qdisc entirely, which removes all attached
/// programs (both ingress and egress). this is the simplest cleanup.
pub fn detachTC(if_index: u32) EbpfError!void {
    const fd = nl.openSocket() catch return EbpfError.DetachFailed;
    defer posix.close(fd);

    deleteClsactQdisc(fd, if_index) catch |e| {
        log.warn("ebpf: failed to delete clsact qdisc on ifindex {d}: {}", .{ if_index, e });
        return EbpfError.DetachFailed;
    };
}

/// create the clsact qdisc on an interface.
///
/// clsact is a special qdisc that provides ingress and egress attachment
/// points for BPF classifiers without actually doing any queuing.
fn createClsactQdisc(fd: posix.fd_t, if_index: u32) nl.NetlinkError!void {
    var buf: [nl.buf_size]u8 align(4) = undefined;
    var mb = nl.MessageBuilder.init(&buf);

    const hdr = try mb.putHeader(
        .RTM_NEWQDISC,
        nl.NLM_F.REQUEST | nl.NLM_F.ACK | nl.NLM_F.CREATE,
        nl.TcMsg,
    );
    const tc = mb.getPayload(hdr, nl.TcMsg);
    tc.family = 0;
    tc._pad1 = 0;
    tc._pad2 = 0;
    tc.ifindex = @intCast(if_index);
    tc.handle = nl.TC_H.CLSACT;
    tc.parent = nl.TC_H.INGRESS;
    tc.info = 0;

    try mb.putAttrStr(hdr, nl.TCA.KIND, "clsact");

    nl.sendAndCheck(fd, mb.message()) catch |e| {
        // EEXIST is fine — qdisc already exists
        if (e == nl.NetlinkError.KernelError) return;
        return e;
    };
}

/// delete the clsact qdisc from an interface.
fn deleteClsactQdisc(fd: posix.fd_t, if_index: u32) nl.NetlinkError!void {
    var buf: [nl.buf_size]u8 align(4) = undefined;
    var mb = nl.MessageBuilder.init(&buf);

    const hdr = try mb.putHeader(
        .RTM_DELQDISC,
        nl.NLM_F.REQUEST | nl.NLM_F.ACK,
        nl.TcMsg,
    );
    const tc = mb.getPayload(hdr, nl.TcMsg);
    tc.family = 0;
    tc._pad1 = 0;
    tc._pad2 = 0;
    tc.ifindex = @intCast(if_index);
    tc.handle = nl.TC_H.CLSACT;
    tc.parent = nl.TC_H.INGRESS;
    tc.info = 0;

    try nl.sendAndCheck(fd, mb.message());
}

/// add a BPF program as a TC filter on ingress or egress.
fn addBpfFilter(
    fd: posix.fd_t,
    if_index: u32,
    direction: Direction,
    prog_fd: posix.fd_t,
) nl.NetlinkError!void {
    var buf: [nl.buf_size]u8 align(4) = undefined;
    var mb = nl.MessageBuilder.init(&buf);

    const parent = switch (direction) {
        .ingress => nl.TC_H.CLSACT | nl.TC_H.MIN_INGRESS,
        .egress => nl.TC_H.CLSACT | nl.TC_H.MIN_EGRESS,
    };

    // protocol field goes in the upper 16 bits of info (network byte order)
    // priority goes in the lower 16 bits
    const eth_p_all: u32 = 0x0003;
    const priority: u32 = 1;
    const info: u32 = (std.mem.nativeToBig(u16, @truncate(eth_p_all)) |
        @as(u32, 0)) | (priority << 16);

    const hdr = try mb.putHeader(
        .RTM_NEWTFILTER,
        nl.NLM_F.REQUEST | nl.NLM_F.ACK | nl.NLM_F.CREATE | nl.NLM_F.EXCL,
        nl.TcMsg,
    );
    const tc = mb.getPayload(hdr, nl.TcMsg);
    tc.family = 0;
    tc._pad1 = 0;
    tc._pad2 = 0;
    tc.ifindex = @intCast(if_index);
    tc.handle = 0;
    tc.parent = parent;
    tc.info = info;

    try mb.putAttrStr(hdr, nl.TCA.KIND, "bpf");

    // nested TCA_OPTIONS containing the BPF fd and flags
    const options = try mb.startNested(hdr, nl.TCA.OPTIONS);

    try mb.putAttrU32(hdr, nl.TCA.BPF_FD, @intCast(prog_fd));
    try mb.putAttrStr(hdr, nl.TCA.BPF_NAME, "yoq");
    try mb.putAttrU32(hdr, nl.TCA.BPF_FLAGS, nl.TCA_BPF.FLAG_ACT_DIRECT);

    mb.endNested(options);

    try nl.sendAndCheck(fd, mb.message());
}

// -- capability check --

/// check if BPF is supported on this system.
///
/// tries to create a minimal hash map — if it fails (typically EPERM
/// or ENOSYS), BPF is not available. the test map is immediately closed.
pub fn isSupported() bool {
    const fd = BPF.map_create(.hash, 4, 4, 1) catch return false;
    posix.close(fd);
    return true;
}

// -- tests --

test "patchMapFd sets src_reg and imm" {
    var insn = BPF.Insn{
        .code = BPF.LD | BPF.IMM | BPF.DW,
        .dst = 0,
        .src = 0,
        .off = 0,
        .imm = 0,
    };

    patchMapFd(&insn, 42);
    try std.testing.expectEqual(@as(u4, BPF.PSEUDO_MAP_FD), insn.src);
    try std.testing.expectEqual(@as(i32, 42), insn.imm);
}

test "patchMapFd with negative fd value" {
    // fds should always be positive, but test the mechanics
    var insn = BPF.Insn{
        .code = BPF.LD | BPF.IMM | BPF.DW,
        .dst = 0,
        .src = 0,
        .off = 0,
        .imm = 0,
    };

    patchMapFd(&insn, 7);
    try std.testing.expectEqual(@as(i32, 7), insn.imm);
    try std.testing.expectEqual(@as(u4, BPF.PSEUDO_MAP_FD), insn.src);
}

test "direction enum" {
    // verify the direction enum works as expected
    try std.testing.expectEqual(Direction.ingress, Direction.ingress);
    try std.testing.expect(Direction.ingress != Direction.egress);
}

test "isSupported returns a boolean" {
    // we can't guarantee BPF is available in CI, but we can verify
    // the function doesn't crash and returns a valid bool
    const result = isSupported();
    try std.testing.expect(result == true or result == false);
}

test "createMap returns fd or error" {
    // try creating a map — may fail without CAP_BPF
    const result = createMap(.hash, 4, 4, 16);
    if (result) |fd| {
        try std.testing.expect(fd >= 0);
        posix.close(fd);
    } else |_| {
        // expected in unprivileged environments
    }
}
